-- AlterTable
ALTER TABLE `BacktestingJobs` ADD COLUMN `StrategyCode` VARCHAR(191) NOT NULL DEFAULT '';

-- CreateTable
CREATE TABLE `StrategiesCode` (
    `id` VARCHAR(191) NOT NULL,
    `Name` VARCHAR(191) NOT NULL DEFAULT '',
    `Text` VARCHAR(191) NOT NULL DEFAULT '',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `editedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
